apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: default
spec:
  ports:
  - port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
  sessionAffinity: None
  type: ClusterIP
